cs/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('index/', include('station.urls'))
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login, name='login'),
    path('login_action/', views.login_action, name='login_action')
]

station/urls.py
from django.urls import path
from . import views

app_name = 'station'
urlpatterns = [
    path('', views.index, name='ListCS')
]

login/models.py
from django.db import models


class Users(models.Model):
    userTel = models.CharField(primary_key=True, max_length=12)
    userName = models.CharField(max_length=16)
    userMail = models.CharField(max_length=20)
    userPwd = models.CharField(max_length=20)

    def __str__(self):
        return self.userName

map/models.py
from django.db import models

# Create your models here.

station/models.py
from django.db import models
from login.models import Users


class Cs(models.Model):
    csId = models.IntegerField(primary_key=True)
    csAdd = models.CharField(max_length=50)
    csStates = models.BooleanField()
    csFreeTime = models.TimeField(auto_now=True)

    def __str__(self):
        return self.csAdd+self.csId.__str__()+'号'


class UserCs(models.Model):
    userTel = models.ForeignKey(Users, on_delete=models.DO_NOTHING)
    csId = models.ForeignKey(Cs, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.userTel.__str__() + '关注了'+self.csId.__str__()+'充电桩'

login/forms.py
from django import forms


class UserForm(forms.Form):
    inputTel = forms.CharField(label='inputTel', max_length=12)
    inputPassword = forms.CharField(label='inputPassword', widget=forms.PasswordInput())

login/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from login.forms import UserForm
from login.models import Users


def login(request):
    return render(request, 'login.html')


def login_action(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            tel = uf.cleaned_data['inputTel']
            pwd = uf.cleaned_data['inputPassword']
            user = Users.objects.filter(userTel=tel, userPwd=pwd)
            if user:
                response = HttpResponseRedirect('/index/')
                response.set_cookie('user', tel, 3600)
                session_user = Users.objects.get(userTel=tel)
                request.session['userTel'] = session_user.userTel
                request.session['userName'] = session_user.userName
                request.session['userMail'] = session_user.userMail
                return HttpResponseRedirect('/index/')
            else:
                return render(request, 'login.html')
    else:
        return render(request, 'login.html')

map/views.py
from django.shortcuts import render

# Create your views here.

station/views.py
from django.shortcuts import render
from station.models import Cs


def index(request):
    cs_add_state = CsAddState()
    cs_add_state.__init__()
    css = Cs.objects.all()
    return render(request, 'ListCS.html', {"css": css, "csAddState": cs_add_state})


def show_common(request, cs_add=None):
    cs_add_state = CsAddState()
    cs_add_state.state = 1
    cs_add_state.cs_add = cs_add
    if cs_add is not None:
        css = Cs.objects.filter(csAdd="精思苑"+cs_add.__str__()+"号楼")
    else:
        css = Cs.objects.all()
    print("*********show_common*******")
    return render(request, 'ListCS.html', {"css": css, "csAddState": cs_add_state})


def show_free(request, cs_add=None):
    cs_add_state = CsAddState()
    cs_add_state.state = 2
    cs_add_state.cs_add = cs_add
    css = Cs.objects.all()
    print("*********show_free*******")
    return render(request, 'ListCS.html', {"css": css, "csAddState": cs_add_state})


def show_focus(request, cs_add=None):
    cs_add_state = CsAddState()
    cs_add_state.state = 3
    cs_add_state.cs_add = cs_add
    css = Cs.objects.all()
    print("*********show_focus*******")
    return render(request, 'ListCS.html', {"css": css, "csAddState": cs_add_state})


class CsAddState(object):
    def __init__(self):
        self.state = 1
        self.cs_add = 1

templates/ListCS.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <style>

        body {
            background-color: aliceblue;
        }

        #Home {
            margin-left: 8.4%;
        }

        #user:hover, #user:focus {
            color: #FFFF;
            text-decoration: none;
        }

        #user {
            position: absolute;
            font-size: large;
            color: #9d9d9d;
            right: 4%;
            top: 25%;

        }

        .logo {
            position: absolute;
            right: 10%;
            top: 5px;
            width: 40px;
            height: 40px;
            border-radius: 100px;
        }

        .logo:hover {
            width: 42px;
            height: 42px;
        }

        .dropdown-menu {
            margin-top: 50px;
            left: 90%;
            right: 0px;
        }

        .page {
            position: fixed;
            top:800px;
            {#margin-top: 60%;#}
        }

        .logoMark {
            width: 100px;
            height: 100px;
            margin-top: 10%;
            border-radius: 100px;
        }

        .listCS {
            margin-top: 1%;
            height: 800px;
            background-color: aqua;
        }

        .ls {
            font-size: large;
            margin-top: 30px;
            margin-left: 5%;
            text-align: center;
        }

        .listNav {
            margin-top: 1%;
        }

        .csid {
            text-align: center;
        }


    </style>


</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="nav-header">

            <img class="logo" src="{% static "/img/logo.png" %}">

            <a href="#" id="user" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">lvscf </a>
            <div class="dropdown">
                <ul class="dropdown-menu">
                    <li><a href="#">修改信息</a></li>
                    <li><a href="#">切换用户</a></li>
                    <li><a href="#">退出</a></li>
                </ul>
            </div>
           <a class="navbar-brand" id="Home" href="#">Home</a> {% comment %}页面跳转去主页{% endcomment %}
        </div>

    </div>
</nav>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 "></div>
        <div class="col-md-2 sbe">

            <img class="logoMark center-block" src="{% static "/img/logo.png" %}">
            <ul class="nav  nav-stacked ls ">
                <li><a href='{% url 'station:show_common' 1 %}'>精思苑1号楼</a></li>
                <li><a href='{% url 'station:show_common' 2 %}'>精思苑2号楼</a></li>
                <li><a href='{% url 'station:show_common' 3 %}'>精思苑3号楼</a></li>
                <li><a href='{% url 'station:show_common' 4 %}'>精思苑4号楼</a></li>
            </ul>

        </div>
        <div class="col-md-1 "></div>
        <div class="col-md-7 listCS">

            <ul class="nav nav-tabs listNav">
                {% if csAddState is not None %}
                <li role="presentation" {% if csAddState.state is 1 %} class="active" {% endif %}><a href="{% url 'station:show_common' csAddState.cs_add %}">所有充电桩</a></li>
                <li role="presentation" {% if csAddState.state is 2 %} class="active" {% endif %}><a href="{% url 'station:show_free' csAddState.cs_add %}">空闲中</a></li>
                <li role="presentation" {% if csAddState.state is 3 %} class="active" {% endif %}><a href="{% url 'station:show_focus' csAddState.cs_add %}">已关注</a></li>
                 {% endif %}
            </ul>

            <div class="panel panel-default ">
                <!-- Default panel contents -->

                <!-- Table -->
                <table class="table ">
                    <tr>
                        <th>充电桩编号</th>
                        <th>充电桩位置</th>
                        <th>空闲状态</th>
                        <th>距离空闲时间</th>
                        <th>是否关注</th>
                    </tr>
                    {% for cs in css %}
                    <tr>
                        <td class="csid">{{ cs.csId }}</td>
                        <td >{{ cs.csAdd }}</td>
                         <td >{{ cs.csStates }}</td>
                        <td >{{ cs.csFreeTime}}</td>

                    </tr>
                    {% endfor %}
                </table>
            </div>

            <nav class="page" aria-label="Page navigation">
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
                </nav>
        </div>


        <div class="col-md-1"></div>
    </div>
</div>


</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>快充呀</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static "css/login.css"%}">
</head>
<body >


     <div class="register">
         <a id="register1" href="#">注册</a>
         <a href="#">忘记密码</a>
     </div>

     <form class="form-signin text-center" action="{% url 'login:login_action' %}"  method = 'post'>
          {% csrf_token %}
          {{uf.as_p}}
         <img class="logo" src="{% static "/img/logo.png"%}">
         <h1 class="h3 mb-3 font-weight-normal">欢迎登陆</h1>
         <label for="inputTel" class="sr-only">Telephone</label>
         <input type="tel" id="inputTel" name="inputTel" class="form-control" placeholder="Telephone" >
         <label for="inputPassword" class="sr-only">Password</label>
         <input type="password" name="inputPassword" id = "inputPassword" class="form-control" placeholder="Password" required>
         <div class="checkbox mb-3">
             <label>
                 <input type="checkbox" value="remember-me"> 记住密码
             </label>
         </div>
         <button class="btn btn-lg btn-primary btn-block" type="submit" id="login"  >登录</button>

         <div class="myMark">充电桩</div>
     </form>


</body>
</html>